### ISSUE TITLE
Jekyll Talk is down ... any idea when it might be back??

### ISSUE THREAD

**Issue by flaturtha** [jekyll/talk.jekyllrb.com#2]
I've got a couple critical issues I need some advice/input on for my Jekyll site but the Jekyll Talk has been dead for several days. I've tried to access it on Mac Chrome & Safari, iPad Chrome & Safari but I get the same error: "This site can’t be reached."

Where else can I get help on Jekyll?

Thank you,
Rich

**Comment by parkr** [comment]
Hey! I'm really sorry about the outage. Our forums are currently experiencing a sustained outage due to a dispute between our provider and a third-party. I'm in touch with our provider and am doing all I can. Unfortunately, I do not have a recent full backup of the forum so we can't just spin up a new instance.

We have a list of other resources at https://jekyllrb.com/help/. Have you checked that list?

**Comment by flaturtha** [comment]
Yeah...I'll check again and figure out the IRC or post on Stack. Sorry
about the provider issues, etc. Ain't it a joy! :)

Feel free to delete this issue. I just didn't know where else to reach out
the best.
